### ISSUE TITLE
No pokemon are found at all

### ISSUE THREAD

**Issue by Annelol** [seikur0/PGO-mapscan-opt#84]
No errors, but no pokemons either

> [+] Distributing 2107 locations to 40 threads.
> [+] Run #1, Time: 10:48:42, ID: 1, Location: (#), Interval: 180 s
> [+] Finished: 2.0 %
> [+] Finished: 4.0 %
> [+] Finished: 6.0 %
> --yadayadayada--
> 
> [+] Distributing 2107 locations to 99 threads.
> [+] Run #1, Time: 10:55:45, ID: 1, Location: (#), Interval: 180 s
> [+] Finished: 2.0 %
> [+] Finished: 4.0 %
> [+] Finished: 6.0 %
> --yadayadayada--
> [+] Finished: 84.0 %
> [+] Finished: 86.0 %
> [+] Finished: 88.0 %
> [+] Finished: 90.0 %
> [+] Finished: 100 %
> 
> [+] 2107 of 2107 cells detected as empty during last run.
> [+] Non-empty heartbeats reached a maximum of 0 retries, allowed: 1.
> [+] Average number of retries was 0.0, total number 0.
> [+] Scan Time: 362 s
> [+] Sleeping for 0 seconds...

**Comment by seikur0** [comment]
edit:
Still working for me, but others seem to have that problem as well. I literally tried using the freshly downloaded tool and then using the same accounts and same location as one of them and it worked while it came up as empty for them.

Okay so everyone with that problem is invited to set the variables in line 103, 105 and 120 to
a) 'time_hb = 10 tries = 5 locktime = 0.1
b) 'time_hb = 15 tries = 6 locktime = 0.2

b is more extreme than a, let's see if that makes it work. Also how would you guys describe the quality and speed of your internet connection in general?

**Comment by Annelol** [comment]
will try with those variables and report back, internet connection shouldnt be a problem for me since its hosted on a VPS

**Comment by Annelol** [comment]
No luck with either scenario a or b, still comes up empty

**Comment by hanscts** [comment]
no luck for me either. For me it stops at...

```
[+] Distributing 2107 locations to 40 threads.
[+] Run #1, Time: 10:48:42, ID: 0, Location: (#), Interval: 900 s
```

... and doesn't even show Finished blablabla

I'm on ADSL @ around 10mbps.

**Comment by c00ni** [comment]
I also tried a and b with several minutes between each try and also coming up empty.

Internet connection is extremely reliable, never drops out. Also hovering around 10mbps ADSL.
As mentioned earlier, other mapping tools return pokemon in the same area, same accounts, same computer/internet connection.

@hanscts you're probably not seeing % complete because it takes so long for the 40 workers to hit 2% of 2107 locations. Make your radius much smaller for testing purposes (and you might as well use less workers too)

**Comment by seikur0** [comment]
It doesn't stop, it's just slow with the a and b settings. But anyway, doesn't seem like they work. @hanscts are you using it on a VPS or some cloud server as well?

An idea, that just came to mind is, which altitude are you guys using? I just tested it with 0 and it came up empty. I think pgoapi normally overwrites a zero altitude automatically with something, so that could explain it.

**Comment by c00ni** [comment]
I was using 0 alt. Will try another value.

Mine is a home internet connection.

**Comment by c00ni** [comment]
Oh my god it works. Showing pokemon again.
(I tried 12)

**Comment by Annelol** [comment]
I tried with altitude 0, 3, 5 and 10 (I think 10 is the actual altitude of the lat/lng Im using) all came up empty

edit: 12 doesnt work for me either ;)

**Comment by hanscts** [comment]
@c00ni I changed range to smaller value and can see scan %.
@seikur0 I'm using a home connection. tried a few different altitudes, including 12, still nothing. spawn0.txt is not growing at all.

**Comment by seikur0** [comment]
Okay so it can handle an altitude of 0 now, I'd still advise you to use a more non-suspicious one though ;) I'll keep looking into it, Annelol and hanscts.

**Comment by hanscts** [comment]
@seikur0 do you think it's related to encrypt.so? This is the only file that is potentially different between all of us.

**Comment by seikur0** [comment]
I made a new branch, bugfix-test, and changed the uk6.py file in that, so it puts out the hexed location values. I think it's that function again. Can you guys give me some output of that? I want the lines, that start with "DEBUG: "

I don't think it's related to encrypt.so, it gives an error if it's the wrong one for your setup.

Could it be, that it was the zero altitude for both of you guys as well and right now your IPs got soft-banned for 15-30 minutes because of too many tries? It may help to wait 30 minutes instead of doing anything.

**Comment by thisIsLiving** [comment]
I was having the same issues and I tried using an altitude of 12 and it worked for me. I didn't use the bug-fix branch.

**Comment by seikur0** [comment]
One customer less to serve :D

**Comment by hanscts** [comment]
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 732, in run
    h = heartbeat(location, self.account)
  File "main0.py", line 547, in heartbeat
    response = get_profile(1, location, account, m1)
  File "main0.py", line 497, in get_profile
    response = api_req(location, account, account['api_url'], account['access_token'], req, useauth=account['auth_ticket'])
  File "main0.py", line 407, in api_req
    sig.location_hash1 = generateLocation1(ticket_serialized, location[0], location[1], location[2])
  File "/home/user/bin/PGO-mapscan-opt-bugfix-test/uk6.py", line 43, in generateLocation1
    locationBytes = d2h(lat) + d2h(lng) + d2h(alt)
  File "/home/user/bin/PGO-mapscan-opt-bugfix-test/uk6.py", line 35, in d2h
    sys.stdout.write('DEBUG: ' + hex_str + '\n')
NameError: global name 'sys' is not defined
```

EDIT: same error for all threads

**Comment by seikur0** [comment]
Forgot that import, sry. Retry with the updated one. Also there is no need to use many accounts for this tests, just 1-4 would be enough.

**Comment by hanscts** [comment]
how many lines do you need? don't want to wall spam... :) the below is just half of what appeared before "Finished 2%"

```
DEBUG: c042e7a28e792bc5
DEBUG: 406224ce2800130
DEBUG: 402a00000000000
DEBUG: c042e7a28e792bc5
DEBUG: 406224ce2800130
DEBUG: 402a00000000000
```

**Comment by seikur0** [comment]
Okay, these look fine. At least that's working I guess :P (I'll shorten your comment for better readability.)

edit:
Have you tried not doing anything for 30 minutes and then retrying?

**Comment by hanscts** [comment]
not yet. i'll stop everything for 30mins from now and report back.

**Comment by nudl3r** [comment]
Same problem here. 
Made a few new accounts to rule out a soft ban and still can't find any pokemon (also spawns file remains empty).

It the error message for banned IP still there?

**Comment by seikur0** [comment]
The ip gets soft-banned not the accounts.

**Comment by nudl3r** [comment]
whoops
this would make sense... I will try it again in an hour or so.

Thanks for your help and all :)

**Comment by seikur0** [comment]
Okay, I hope this'll fix it!

**Comment by hanscts** [comment]
if you connect to VPN before starting the server it would be on different IP.

edit: just tried through VPN. Still nothing.

**Comment by Annelol** [comment]
I waited about an hour and 15 minutes before trying again with the debug branch

edit by seikur0: output removed for visibility

**Comment by seikur0** [comment]
Yeah these lead to nothing, is it working now Annelol? Switch back to the main branch.

**Comment by Annelol** [comment]
No, still no pokemon found =(

**Comment by seikur0** [comment]
Okay, give me the coordinates.

**Comment by Annelol** [comment]
"coordinates":{"lat": 52.027892,"lng": 5.556565,"alt": 12}

but also tried with other coordinates in the same city, and even in a completely different country

**Comment by nudl3r** [comment]
Ok, I tested another map (https://github.com/favll/pogom) and it works, so I can definitely rule out an IP ban.

**Comment by seikur0** [comment]
nudl3r are you on the newest update? The version before had an issue with altitudes of 0.

Annelol I'll try these coordinates in ~20 minutes. Maybe I can find something about it :/

**Comment by hanscts** [comment]
update: just retried and still nothing.

**Comment by nudl3r** [comment]
Yes, I am on the latest update.

**Comment by joeker94** [comment]
Mine is running, map loaded, but no pokemon

**Comment by seikur0** [comment]
@Annelol: I tried your location and there is nothing wrong with it, lots of pokemon around for me :/ Can you try doing an ip reconnect and then making a completely new account and using only that for one scan? (You can run it with the '-tos' Parameter to make it accept the tos, so it should work.)

**Comment by Annelol** [comment]
I have a static ip from the vps hosting, but I did try a new account, did not resolve the issue =( still only 'finished x%' messages nothing else.

**Comment by seikur0** [comment]
Okay, can you try that other map nudl3r mentioned: https://github.com/favll/pogom on that vps? If it's the same as in no pokemon get found, then that ip is banned.

**Comment by Annelol** [comment]
That map works fine, finds pokemon and everything

**Comment by seikur0** [comment]
Well it's working for most users with the new updates. And if you're up to date I really don't have an idea, how to help you.

**Comment by seikur0** [comment]
As an update I tried running it on a vps as well and didn't get pokemon. I'll compare pogoapi and my lightweight version tomorrow side by side to see why.

**Comment by NHLGames** [comment]
I believe they've banned certain popular VPS providers like Digitalocean and Linode.  You might have more luck running one from a less known company.

**Comment by seikur0** [comment]
I used a proxy, but it may be the case, that I got a soft-banned one. Tomorrow I can say more about this.

**Comment by hanscts** [comment]
Just woke up and pull the latest code to try again. Still returning nothing. :(
Not sure what else I can try.

**Comment by DanHazard** [comment]
I think it has to do with banning.  I accidentally ran two occuracnes at once today and was banned after.  Now I can't scan for more than an hour without being hit with a ban.

**Comment by Annelol** [comment]
It doesnt have to do with banning, I havent been able to scan with this program at all since unknown6, other maps work fine with the same accounts and ip

**Comment by seikur0** [comment]
Well I tried directly with pogoapi and it didn't find any pokemon as well on pythonanywhere vps.

I can't create a situation, in which one tool works and mine not, so I can't investigate this at all.

Annelol, if other tools are working on your vps, would you give me access to your vps, so I can test stuff?

**Comment by nudl3r** [comment]
@seikur0 I can give you access to my server as well, if you want. Just message me what you need (default linux user? root access?).

**Comment by seikur0** [comment]
I need to be able to run my tool and another one (in python) that's working for you side by side, so if you could prepare that it would be good. Then also some good gui editor with python syntax recognition. Default linux user should be enough. Is that possible? xD

**Comment by nudl3r** [comment]
Sent you a message on reddit =)

**Comment by dslize** [comment]
So, I've been using this map before the unknown6 changes but haven't been playing recently. I downloaded the newest files and tried to set it up like before on my Linux inside Virtualbox : no pokemon showing up, just like the others in this issue, all cells being detected as empty. The Pogom map works, but this one sadly doesn't. Tried a fresh setup, reinstalling requirements etc., nothing helped.

Then I tried setting up everything on my host OS (Windows) and look: it's working now. :)
I have no clue why it isn't working on my linux tho. Could Virtualbox be the reason? I don't know why it should be, but the OS is the only thing I changed, took the old settings etc.
Not sure if this is applicable for the others here but that's at least how I got it working, thought I'd share.

**Comment by seikur0** [comment]
Which linux distribution and version did you use? Because that would be the easiest way for me to test stuff. It seems related to some difference between linux and windows.

**Comment by hanscts** [comment]
I was on Lubuntu 16.04. Tested on Ubuntu 16.04 as well. Didn't test on Windows as I don't have a spare OS to test it.

**Comment by dslize** [comment]
Ubuntu 16.04 is the distribution and version it isn't working for me

**Comment by Annelol** [comment]
Ubuntu 14.04, no luck

**Comment by nudl3r** [comment]
I'm on Ubuntu 14.04, too. Will try it on my local PC today.

**Comment by seikur0** [comment]
Fixed. #justlinuxthings

**Comment by Annelol** [comment]
Works <3

**Comment by nudl3r** [comment]
Works!
You're the best.

**Comment by nudl3r** [comment]
Sorry for opening this issue again, but since yesterday this problem is back.
![pgo](https://cloud.githubusercontent.com/assets/20855722/17803246/9602efca-65f5-11e6-9b23-32ed7dc20bf2.png)
Possible IP ban (other tools don't work, too) or another API change? Do you know if there's a way to check this?

**Comment by seikur0** [comment]
It means, that these Accounts were permanently banned. Remove them from the settings. (they're also written to a file named banned.txt) And since you have Accounts remaining, you might have an IP softban as well atm.

**Comment by nudl3r** [comment]
IP softban = not permanent? Are there any permanent IP bans at all?
And yes, the other accounts I configured should work.

**Comment by seikur0** [comment]
Not permanent as in wait half an hour or so without connecting to niantic or do a reconnect. There are permanent IP bans, vps and cloudhosting providers get blacklisted. It'll show you a specific error message stating that your ip was banned in that case.
